version: "2.1"
services:
  wireguard:
    # command: tail -f /dev/null
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=${WIREGUARD_HOST_IP} #optional
      - SERVERPORT=51820 #optional
      - PEERS=3 #optional
      # - PEERDNS=auto #optional
      # - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./data/config:/config
      # - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    privileged: true 
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      main:
networks:
  main:
    driver: bridge
    # gateway: 192.168.2.1 # set the gateway for when multiple interfaces are used. Fixes routing when on LAN 

